import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "@/shared/components/Navbar";


const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"], // add bold weights
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Qvision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${montserrat.className} h-screen antialiased`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
